In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [12]:
data = pd.read_csv('D:\\souha\\Churn_Modelling.csv', encoding='latin1')

In [13]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [14]:
X=data.iloc[:,3:13].values #takes all the data from column 3 to 13 not includind 13 and store them in X
Y=data.iloc [:,13].values  #puts all the valiables of the ccolumn 13 into the variable Y

In [15]:
print (X )


[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [16]:
print (Y )

[1 0 1 ... 1 1 0]


In [17]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])
    #transforming the none numrical columns (gender) into num one 

In [18]:
print (X )


[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [19]:
from sklearn.compose import ColumnTransformer

In [20]:
ct= ColumnTransformer ([('ohe',OneHotEncoder(),[1])],remainder='passthrough') #transformer la colonne de Geogra^phy into num

In [21]:
X= np.array(ct.fit_transform(X), dtype = 'str')

In [22]:
X=X[:,1:]

In [23]:
print (X )  #0 0 -->france / 0 1 --> Spain / 1 0 --> germany


[['0.0' '0.0' '619' ... '1' '1' '101348.88']
 ['0.0' '1.0' '608' ... '0' '1' '112542.58']
 ['0.0' '0.0' '502' ... '1' '0' '113931.57']
 ...
 ['0.0' '0.0' '709' ... '0' '1' '42085.58']
 ['1.0' '0.0' '772' ... '1' '0' '92888.52']
 ['0.0' '0.0' '792' ... '1' '0' '38190.78']]


In [24]:
from sklearn.model_selection import train_test_split 

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc=StandardScaler()

In [28]:
X_train=sc.fit_transform(X_train)  #prend chaque valeur de x fit it and transform it into an array 
X_test= sc.fit_transform(X_test)

In [29]:
import pandas as pd 
print (X_train)

[[-0.5698444   1.74309049  0.16958176 ...  0.64259497 -1.03227043
   1.10643166]
 [ 1.75486502 -0.57369368 -2.30455945 ...  0.64259497  0.9687384
  -0.74866447]
 [-0.5698444  -0.57369368 -1.19119591 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [-0.5698444  -0.57369368  0.9015152  ...  0.64259497 -1.03227043
   1.41231994]
 [-0.5698444   1.74309049 -0.62420521 ...  0.64259497  0.9687384
   0.84432121]
 [ 1.75486502 -0.57369368 -0.28401079 ...  0.64259497 -1.03227043
   0.32472465]]


In [30]:
pd.DataFrame(X_train)

0         1         2         3         4         5         6   \
0    -0.569844  1.743090  0.169582 -1.091687 -0.464608  0.006661 -1.215717   
1     1.754865 -0.573694 -2.304559  0.916013  0.301026 -1.377440 -0.006312   
2    -0.569844 -0.573694 -1.191196 -1.091687 -0.943129 -1.031415  0.579935   
3    -0.569844  1.743090  0.035566  0.916013  0.109617  0.006661  0.473128   
4    -0.569844  1.743090  2.056114 -1.091687  1.736588  1.044737  0.810193   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.754865 -0.573694 -0.582970 -1.091687 -0.656016 -0.339364  0.703104   
7996 -0.569844  1.743090  1.478815 -1.091687 -1.613058 -0.339364  0.613060   
7997 -0.569844 -0.573694  0.901515  0.916013 -0.368904  0.006661  1.361474   
7998 -0.569844  1.743090 -0.624205 -1.091687 -0.081791  1.390762 -1.215717   
7999  1.754865 -0.573694 -0.284011 -1.091687  0.875251 -1.377440  0.511364   

            7         8         9         10  
0     0.809503  0.642595 -1.032270  1.106432  
1    -0.921591  0.642595  0.968738 -0.748664  
2    -0.921591  0.642595 -1.032270  1.485335  
3    -0.921591  0.642595 -1.032270  1.276528  
4     0.809503  0.642595  0.968738  0.558378  
...        ...       ...       ...       ...  
7995  0.809503  0.642595  0.968738  1.091330  
7996 -0.921591  0.642595  0.968738  0.131760  
7997  0.809503  0.642595 -1.032270  1.412320  
7998  0.809503  0.642595  0.968738  0.844321  
7999 -0.921591  0.642595 -1.032270  0.324725  

[8000 rows x 11 columns]

In [31]:
!pip install tensorflow  

In [32]:
!pip install keras 

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [34]:
classifier = Sequential()

In [36]:
classifier.add (Dense (units=6,kernel_initializer='uniform',activation='relu',input_dim=11))

In [37]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))

In [38]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))

In [39]:
classifier.compile (optimizer ='adam',loss='binary_crossentropy',metrics=['accuracy'])  #to compile the ANN 

In [40]:
classifier.fit(X_train,y_train ,batch_size =10,epochs=100)

Epoch 1/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 659us/step - accuracy: 0.7946 - loss: 0.5595
Epoch 2/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - accuracy: 0.8031 - loss: 0.4194
Epoch 3/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.7971 - loss: 0.4235
Epoch 4/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 590us/step - accuracy: 0.8189 - loss: 0.4302
Epoch 5/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 607us/step - accuracy: 0.8259 - loss: 0.4076
Epoch 6/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 607us/step - accuracy: 0.8351 - loss: 0.4114
Epoch 7/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step - accuracy: 0.8249 - loss: 0.4245
Epoch 8/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 653us/step - accuracy: 0.8329 - loss: 0.4117
Epoch 9/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - accuracy: 0.8376 - loss: 0.4065
Epoch 10/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 591us/step - accuracy: 0.8309 - loss: 0.4142
Epoch 11/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 0s 587us/step - accuracy: 0.8399 - loss: 0.4043
Epoch 12/100
800/80

In [75]:
y_pred =classifier.predict(X_train)
y_pred =(y_pred >0.5)

250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step


In [90]:
print("Shape of y_test:", y_test.shape)
print("Shape of y_pred:", y_pred.shape)


Shape of y_test: (2000,)
Shape of y_pred: (8000, 1)


In [91]:
from sklearn.metrics import confusion_matrix , accuracy_score 
cm =confusion_matrix (y_train,y_pred)
print (cm  )  #(1505 value predict right and 91 were false

[[6178  190]
 [1127  505]]


In [93]:
accuracy_score  (y_train,y_pred)

0.835375

In [94]:
print (y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [ True]]


In [95]:
y_pred_binary = y_pred.astype(int)


In [96]:
print (y_pred_binary )

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [1]]


In [98]:
predictions_series = pd.Series(y_pred_binary .flatten(), index=data.index[:len(X_train)], name='Predicted_values')


In [99]:
data['Predicted_values'] = predictions_series


In [100]:
print(data['Predicted_values'])

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ... 
9995    NaN
9996    NaN
9997    NaN
9998    NaN
9999    NaN
Name: Predicted_values, Length: 10000, dtype: float64


In [101]:
print (data.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  Predicted_Duration  Predicted_values  
0        101348.88       1            0.189284               0.0  
1        112542.58      